# pylint: disable=syntax-error

import pandas as pd
import yaml

from snakemake.utils import min_version

min_version("5.0")

shell.prefix("set -euo pipefail;")

params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv")


# Other variables
POPULATIONS = samples["population"].drop_duplicates().values.tolist()
PAIRS = ["pe_pe", "pe_se"]
CHROMOSOMES = features["chromosomes"].split(" ")
ENDS = "1 2 u".split(" ")


include: "rules/folders.smk"
include: "rules/generic.smk"
include: "rules/raw.smk"
include: "rules/qc.smk"
include: "rules/map.smk"
include: "rules/mpileup.smk"
include: "rules/popoolation.smk"
include: "rules/hp.smk"
include: "rules/sync.smk"
include: "rules/fst.smk"
include: "rules/reports.smk"


rule all:
    input:
        # rules.qc.input,
        # rules.map.input,
        # rules.mpileup_subsampled.input,
        rules.popoolation_d.input,
        rules.popoolation_pi.input,
        rules.popoolation_theta.input,
        expand(HP_PLOTS / "{population}.pdf", population=POPULATIONS),
        rules.fst.input,
        rules.reports.input,


rule clean:
    shell:
        """
        if [[ -d results ]]; then
            rm -r results/
        fi
        """
