channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - openjdk =21.0.2
  - perl =5.32.1
  - pigz =2.8
  - python =3.12.3
  - r-argparse =2.2.3
  - r-tidyverse =2.0.0
  - samtools =1.20
