channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa-mem2 =2.2.1
  - gatk4 =4.5.0.0
  - pigz =2.8
  - python =3.12.3
  - samtools =1.20
  - r-tidyverse =2.0.0
  - r-tidyquant =1.0.7
