# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .snakemake/conda
          key: snakemake-conda

      - name: Download environments
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --conda-create-envs-only
            --conda-frontend mamba
            --cores 1

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --all-temp
